LOCK THROTTLE TO 1.
STAGE.
UNTIL SHIP:MAXTHRUST > 0 {
  STAGE.
  WAIT 0.1.
}

LOCK TARGETPITCH TO 88.963 - 1.03287 * ALT:RADAR^0.409511.
SET TARGETDIRECTION TO 90.
LOCK STEERING TO HEADING(TARGETDIRECTION, TARGETPITCH).

SET AVAILTHRUST TO SHIP:AVAILABLETHRUST.
IF NOT SHIP:APOAPSIS > 100 {
  IF SHIP:AVAILABLETHRUST < (AVAILTHRUST - 10) {
    STAGE.
    WAIT 1.
    SET AVAILTHRUST TO SHIP:AVAILABLETHRUST.
  }
}
