@LAZYGLOBAL OFF.

// X-10 D AtmosphereAutopilot compatibility probe.
// Purpose: exercise GET/SET for AA suffixes and identify exact failure points.
GLOBAL LOG_FILE IS "0:/x10d_aa_probe.log".

FUNCTION OUT {
  PARAMETER MSG.
  PRINT MSG.
  LOG MSG TO LOG_FILE.
}

OUT(" ").
OUT("===== X-10 D AA probe run @ UT " + ROUND(TIME:SECONDS, 1) + " =====").
OUT("X-10 D AA probe: start").

IF NOT ADDONS:AVAILABLE("AA") {
  OUT("AA PROBE FAIL: ADDONS:AA not available").
  OUT("Likely missing/out-of-date kOS AtmosphereAutopilot bridge").
  OUT("Main pipeline: 0:/Vehicles/X_10_D_new.ks").
  OUT("X-10 D AA probe: end").
} ELSE {

OUT("AA PROBE: ADDONS:AA available").
OUT(" ").
OUT("Suffix presence check:").
OUT(" MODERATEAOA=" + ADDONS:AA:HASSUFFIX("MODERATEAOA")
  + " MAXAOA=" + ADDONS:AA:HASSUFFIX("MAXAOA")
  + " MODERATEG=" + ADDONS:AA:HASSUFFIX("MODERATEG")
  + " MAXG=" + ADDONS:AA:HASSUFFIX("MAXG")).
OUT(" MODERATESIDESLIP=" + ADDONS:AA:HASSUFFIX("MODERATESIDESLIP")
  + " MAXSIDESLIP=" + ADDONS:AA:HASSUFFIX("MAXSIDESLIP")
  + " MODERATESIDEG=" + ADDONS:AA:HASSUFFIX("MODERATESIDEG")
  + " MAXSIDEG=" + ADDONS:AA:HASSUFFIX("MAXSIDEG")).
OUT(" PITCHRATELIMIT=" + ADDONS:AA:HASSUFFIX("PITCHRATELIMIT")
  + " YAWRATELIMIT=" + ADDONS:AA:HASSUFFIX("YAWRATELIMIT")
  + " ROLLRATELIMIT=" + ADDONS:AA:HASSUFFIX("ROLLRATELIMIT")
  + " WINGLEVELER=" + ADDONS:AA:HASSUFFIX("WINGLEVELER")).
OUT(" FBW=" + ADDONS:AA:HASSUFFIX("FBW")
  + " FLYBYWIRE=" + ADDONS:AA:HASSUFFIX("FLYBYWIRE")
  + " COORDTURN=" + ADDONS:AA:HASSUFFIX("COORDTURN")
  + " ROCKETMODE=" + ADDONS:AA:HASSUFFIX("ROCKETMODE")).
OUT(" DIRECTOR=" + ADDONS:AA:HASSUFFIX("DIRECTOR")
  + " DIRECTION=" + ADDONS:AA:HASSUFFIX("DIRECTION")
  + " DIRECTORSTRENGTH=" + ADDONS:AA:HASSUFFIX("DIRECTORSTRENGTH")).
OUT(" CRUISE=" + ADDONS:AA:HASSUFFIX("CRUISE")
  + " PSEUDOFLC=" + ADDONS:AA:HASSUFFIX("PSEUDOFLC")
  + " HEADING=" + ADDONS:AA:HASSUFFIX("HEADING")
  + " ALTITUDE=" + ADDONS:AA:HASSUFFIX("ALTITUDE")
  + " VERTSPEED=" + ADDONS:AA:HASSUFFIX("VERTSPEED")).
OUT(" FLCMARGIN=" + ADDONS:AA:HASSUFFIX("FLCMARGIN")
  + " MAXCLIMBANGLE=" + ADDONS:AA:HASSUFFIX("MAXCLIMBANGLE")
  + " WAYPOINT=" + ADDONS:AA:HASSUFFIX("WAYPOINT")
  + " SPEEDCONTROL=" + ADDONS:AA:HASSUFFIX("SPEEDCONTROL")
  + " SPEED=" + ADDONS:AA:HASSUFFIX("SPEED")).

OUT(" ").
OUT("STEP 1: snapshot mode states").
LOCAL ORIG_DIRECTOR IS FALSE.
LOCAL ORIG_CRUISE IS FALSE.
LOCAL ORIG_FBW IS FALSE.

IF ADDONS:AA:HASSUFFIX("DIRECTOR") { SET ORIG_DIRECTOR TO ADDONS:AA:DIRECTOR. }
IF ADDONS:AA:HASSUFFIX("CRUISE") { SET ORIG_CRUISE TO ADDONS:AA:CRUISE. }
IF ADDONS:AA:HASSUFFIX("FBW") { SET ORIG_FBW TO ADDONS:AA:FBW. }

OUT("  DIRECTOR=" + ORIG_DIRECTOR + " CRUISE=" + ORIG_CRUISE + " FBW=" + ORIG_FBW).

OUT("STEP 2: mode prep (DIRECTOR ON, FBW OFF, CRUISE write skipped)").
// Faulty on this bridge build (kept for reference):
// IF ADDONS:AA:HASSUFFIX("CRUISE") { SET ADDONS:AA:CRUISE TO FALSE. }
OUT("  CRUISE SET skipped (known bridge setter failure).").
IF ADDONS:AA:HASSUFFIX("FBW") { SET ADDONS:AA:FBW TO FALSE. }
IF ADDONS:AA:HASSUFFIX("DIRECTOR") { SET ADDONS:AA:DIRECTOR TO TRUE. }
WAIT 0.2.

OUT("STEP 3: moderation toggles/scalars").
IF ADDONS:AA:HASSUFFIX("MODERATEAOA") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:MODERATEAOA.
  OUT("  MODERATEAOA GET=" + CURRENT_FLAG).
  SET ADDONS:AA:MODERATEAOA TO NOT CURRENT_FLAG.
  SET ADDONS:AA:MODERATEAOA TO CURRENT_FLAG.
}
IF ADDONS:AA:HASSUFFIX("MAXAOA") {
  LOCAL CURRENT_VALUE IS ADDONS:AA:MAXAOA.
  LOCAL UPDATED_VALUE IS CURRENT_VALUE + 0.5.
  OUT("  MAXAOA GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  SET ADDONS:AA:MAXAOA TO UPDATED_VALUE.
  SET ADDONS:AA:MAXAOA TO CURRENT_VALUE.
}
IF ADDONS:AA:HASSUFFIX("MODERATEG") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:MODERATEG.
  OUT("  MODERATEG GET=" + CURRENT_FLAG).
  SET ADDONS:AA:MODERATEG TO NOT CURRENT_FLAG.
  SET ADDONS:AA:MODERATEG TO CURRENT_FLAG.
}
IF ADDONS:AA:HASSUFFIX("MAXG") {
  LOCAL CURRENT_VALUE IS ADDONS:AA:MAXG.
  LOCAL UPDATED_VALUE IS CURRENT_VALUE + 0.5.
  OUT("  MAXG GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  SET ADDONS:AA:MAXG TO UPDATED_VALUE.
  SET ADDONS:AA:MAXG TO CURRENT_VALUE.
}
IF ADDONS:AA:HASSUFFIX("MODERATESIDESLIP") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:MODERATESIDESLIP.
  OUT("  MODERATESIDESLIP GET=" + CURRENT_FLAG).
  SET ADDONS:AA:MODERATESIDESLIP TO NOT CURRENT_FLAG.
  SET ADDONS:AA:MODERATESIDESLIP TO CURRENT_FLAG.
}
IF ADDONS:AA:HASSUFFIX("MAXSIDESLIP") {
  LOCAL CURRENT_VALUE IS ADDONS:AA:MAXSIDESLIP.
  LOCAL UPDATED_VALUE IS CURRENT_VALUE + 0.2.
  OUT("  MAXSIDESLIP GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  SET ADDONS:AA:MAXSIDESLIP TO UPDATED_VALUE.
  SET ADDONS:AA:MAXSIDESLIP TO CURRENT_VALUE.
}
IF ADDONS:AA:HASSUFFIX("MODERATESIDEG") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:MODERATESIDEG.
  OUT("  MODERATESIDEG GET=" + CURRENT_FLAG).
  SET ADDONS:AA:MODERATESIDEG TO NOT CURRENT_FLAG.
  SET ADDONS:AA:MODERATESIDEG TO CURRENT_FLAG.
}
IF ADDONS:AA:HASSUFFIX("MAXSIDEG") {
  LOCAL CURRENT_VALUE IS ADDONS:AA:MAXSIDEG.
  LOCAL UPDATED_VALUE IS CURRENT_VALUE + 0.2.
  OUT("  MAXSIDEG GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  SET ADDONS:AA:MAXSIDEG TO UPDATED_VALUE.
  SET ADDONS:AA:MAXSIDEG TO CURRENT_VALUE.
}

OUT("STEP 4: rate limits and wing leveler").
IF ADDONS:AA:HASSUFFIX("PITCHRATELIMIT") {
  LOCAL CURRENT_VALUE IS ADDONS:AA:PITCHRATELIMIT.
  LOCAL UPDATED_VALUE IS MAX(0.05, CURRENT_VALUE + 0.05).
  OUT("  PITCHRATELIMIT GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  SET ADDONS:AA:PITCHRATELIMIT TO UPDATED_VALUE.
  SET ADDONS:AA:PITCHRATELIMIT TO CURRENT_VALUE.
}
IF ADDONS:AA:HASSUFFIX("YAWRATELIMIT") {
  LOCAL CURRENT_VALUE IS ADDONS:AA:YAWRATELIMIT.
  LOCAL UPDATED_VALUE IS MAX(0.05, CURRENT_VALUE + 0.05).
  OUT("  YAWRATELIMIT GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  SET ADDONS:AA:YAWRATELIMIT TO UPDATED_VALUE.
  SET ADDONS:AA:YAWRATELIMIT TO CURRENT_VALUE.
}
IF ADDONS:AA:HASSUFFIX("ROLLRATELIMIT") {
  LOCAL CURRENT_VALUE IS ADDONS:AA:ROLLRATELIMIT.
  LOCAL UPDATED_VALUE IS MAX(0.05, CURRENT_VALUE + 0.05).
  OUT("  ROLLRATELIMIT GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  SET ADDONS:AA:ROLLRATELIMIT TO UPDATED_VALUE.
  SET ADDONS:AA:ROLLRATELIMIT TO CURRENT_VALUE.
}
IF ADDONS:AA:HASSUFFIX("WINGLEVELER") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:WINGLEVELER.
  OUT("  WINGLEVELER GET=" + CURRENT_FLAG).
  SET ADDONS:AA:WINGLEVELER TO NOT CURRENT_FLAG.
  SET ADDONS:AA:WINGLEVELER TO CURRENT_FLAG.
}

OUT("STEP 5: FBW / alias / turn settings").
IF ADDONS:AA:HASSUFFIX("FBW") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:FBW.
  OUT("  FBW GET=" + CURRENT_FLAG).
  SET ADDONS:AA:FBW TO TRUE.
  WAIT 0.1.
  SET ADDONS:AA:FBW TO CURRENT_FLAG.
}
IF ADDONS:AA:HASSUFFIX("FLYBYWIRE") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:FLYBYWIRE.
  OUT("  FLYBYWIRE GET=" + CURRENT_FLAG).
  SET ADDONS:AA:FLYBYWIRE TO NOT CURRENT_FLAG.
  SET ADDONS:AA:FLYBYWIRE TO CURRENT_FLAG.
}
IF ADDONS:AA:HASSUFFIX("COORDTURN") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:COORDTURN.
  OUT("  COORDTURN GET=" + CURRENT_FLAG).
  SET ADDONS:AA:COORDTURN TO NOT CURRENT_FLAG.
  SET ADDONS:AA:COORDTURN TO CURRENT_FLAG.
}
IF ADDONS:AA:HASSUFFIX("ROCKETMODE") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:ROCKETMODE.
  OUT("  ROCKETMODE GET=" + CURRENT_FLAG).
  SET ADDONS:AA:ROCKETMODE TO NOT CURRENT_FLAG.
  SET ADDONS:AA:ROCKETMODE TO CURRENT_FLAG.
}

OUT("STEP 6: director controls").
IF ADDONS:AA:HASSUFFIX("DIRECTOR") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:DIRECTOR.
  OUT("  DIRECTOR GET=" + CURRENT_FLAG).
  SET ADDONS:AA:DIRECTOR TO TRUE.
  WAIT 0.1.
  SET ADDONS:AA:DIRECTOR TO CURRENT_FLAG.
}
IF ADDONS:AA:HASSUFFIX("DIRECTION") {
  OUT("  DIRECTION SET -> HEADING(SHIP:HEADING, 8):VECTOR").
  SET ADDONS:AA:DIRECTION TO HEADING(SHIP:HEADING, 8):VECTOR.
}
IF ADDONS:AA:HASSUFFIX("DIRECTORSTRENGTH") {
  LOCAL CURRENT_VALUE IS ADDONS:AA:DIRECTORSTRENGTH.
  LOCAL UPDATED_VALUE IS MIN(1, MAX(0, CURRENT_VALUE + 0.05)).
  OUT("  DIRECTORSTRENGTH GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  SET ADDONS:AA:DIRECTORSTRENGTH TO UPDATED_VALUE.
  SET ADDONS:AA:DIRECTORSTRENGTH TO CURRENT_VALUE.
}

OUT("STEP 7: speed control settings").
IF ADDONS:AA:HASSUFFIX("SPEEDCONTROL") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:SPEEDCONTROL.
  OUT("  SPEEDCONTROL GET=" + CURRENT_FLAG).
  SET ADDONS:AA:SPEEDCONTROL TO NOT CURRENT_FLAG.
  SET ADDONS:AA:SPEEDCONTROL TO CURRENT_FLAG.
}
IF ADDONS:AA:HASSUFFIX("SPEED") {
  LOCAL CURRENT_VALUE IS ADDONS:AA:SPEED.
  LOCAL UPDATED_VALUE IS MAX(40, CURRENT_VALUE + 5).
  OUT("  SPEED GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  SET ADDONS:AA:SPEED TO UPDATED_VALUE.
  SET ADDONS:AA:SPEED TO CURRENT_VALUE.
}

OUT("STEP 8: cruise settings (risky, bridge may fail here)").
IF ADDONS:AA:HASSUFFIX("CRUISE") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:CRUISE.
  OUT("  CRUISE GET=" + CURRENT_FLAG).
  // Faulty on this bridge build (kept for reference):
  // OUT("  Attempting: SET ADDONS:AA:CRUISE TO TRUE").
  // SET ADDONS:AA:CRUISE TO TRUE.
  // WAIT 0.2.
  // SET ADDONS:AA:CRUISE TO CURRENT_FLAG.
  OUT("  CRUISE SET skipped (known bridge setter failure).").
}
IF ADDONS:AA:HASSUFFIX("PSEUDOFLC") {
  LOCAL CURRENT_FLAG IS ADDONS:AA:PSEUDOFLC.
  OUT("  PSEUDOFLC GET=" + CURRENT_FLAG).
  // Faulty on this bridge build (kept for reference):
  // SET ADDONS:AA:PSEUDOFLC TO NOT CURRENT_FLAG.
  // SET ADDONS:AA:PSEUDOFLC TO CURRENT_FLAG.
  OUT("  PSEUDOFLC SET skipped (known cruise-controller setter failure).").
}
IF ADDONS:AA:HASSUFFIX("HEADING") {
  LOCAL CURRENT_VALUE IS ADDONS:AA:HEADING.
  LOCAL UPDATED_VALUE IS SHIP:HEADING.
  OUT("  HEADING GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  SET ADDONS:AA:HEADING TO UPDATED_VALUE.
  SET ADDONS:AA:HEADING TO CURRENT_VALUE.
}
IF ADDONS:AA:HASSUFFIX("ALTITUDE") {
  LOCAL CURRENT_VALUE IS ADDONS:AA:ALTITUDE.
  LOCAL UPDATED_VALUE IS CURRENT_VALUE + 100.
  OUT("  ALTITUDE GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  // Faulty on this bridge build (kept for reference):
  // SET ADDONS:AA:ALTITUDE TO UPDATED_VALUE.
  // SET ADDONS:AA:ALTITUDE TO CURRENT_VALUE.
  OUT("  ALTITUDE SET skipped (known cruise-controller setter failure).").
}
IF ADDONS:AA:HASSUFFIX("VERTSPEED") {
  // Faulty on this bridge build (kept for reference):
  // LOCAL CURRENT_VALUE IS ADDONS:AA:VERTSPEED.
  // LOCAL UPDATED_VALUE IS CURRENT_VALUE + 1.
  // OUT("  VERTSPEED GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  OUT("  VERTSPEED GET skipped (NaN/stack fault on this bridge).").
  // Faulty on this bridge build (kept for reference):
  // SET ADDONS:AA:VERTSPEED TO UPDATED_VALUE.
  // SET ADDONS:AA:VERTSPEED TO CURRENT_VALUE.
  OUT("  VERTSPEED SET skipped (known cruise-controller setter failure).").
}
IF ADDONS:AA:HASSUFFIX("FLCMARGIN") {
  // Faulty on this bridge build (kept for reference):
  // LOCAL CURRENT_VALUE IS ADDONS:AA:FLCMARGIN.
  // LOCAL UPDATED_VALUE IS CURRENT_VALUE + 1.
  // OUT("  FLCMARGIN GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  OUT("  FLCMARGIN GET skipped (unsafe cruise-controller read on this bridge).").
  // Faulty on this bridge build (kept for reference):
  // SET ADDONS:AA:FLCMARGIN TO UPDATED_VALUE.
  // SET ADDONS:AA:FLCMARGIN TO CURRENT_VALUE.
  OUT("  FLCMARGIN SET skipped (known cruise-controller setter failure).").
}
IF ADDONS:AA:HASSUFFIX("MAXCLIMBANGLE") {
  // Faulty on this bridge build (kept for reference):
  // LOCAL CURRENT_VALUE IS ADDONS:AA:MAXCLIMBANGLE.
  // LOCAL UPDATED_VALUE IS MIN(89, CURRENT_VALUE + 1).
  // OUT("  MAXCLIMBANGLE GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  OUT("  MAXCLIMBANGLE GET skipped (unsafe cruise-controller read on this bridge).").
  // Faulty on this bridge build (kept for reference):
  // SET ADDONS:AA:MAXCLIMBANGLE TO UPDATED_VALUE.
  // SET ADDONS:AA:MAXCLIMBANGLE TO CURRENT_VALUE.
  OUT("  MAXCLIMBANGLE SET skipped (known cruise-controller setter failure).").
}
IF ADDONS:AA:HASSUFFIX("WAYPOINT") {
  // Faulty on this bridge build (kept for reference):
  // LOCAL CURRENT_VALUE IS ADDONS:AA:WAYPOINT.
  // LOCAL UPDATED_VALUE IS SHIP:GEOPOSITION.
  // OUT("  WAYPOINT GET=" + CURRENT_VALUE + " SET=" + UPDATED_VALUE).
  OUT("  WAYPOINT GET skipped (unsafe cruise-controller read on this bridge).").
  // Faulty on this bridge build (kept for reference):
  // SET ADDONS:AA:WAYPOINT TO UPDATED_VALUE.
  // SET ADDONS:AA:WAYPOINT TO CURRENT_VALUE.
  OUT("  WAYPOINT SET skipped (known cruise-controller setter failure).").
}

OUT("STEP 9: restore mode states").
IF ADDONS:AA:HASSUFFIX("DIRECTOR") { SET ADDONS:AA:DIRECTOR TO ORIG_DIRECTOR. }
// Faulty on this bridge build (kept for reference):
// IF ADDONS:AA:HASSUFFIX("CRUISE") { SET ADDONS:AA:CRUISE TO ORIG_CRUISE. }
OUT("  CRUISE restore skipped (known bridge setter failure).").
IF ADDONS:AA:HASSUFFIX("FBW") { SET ADDONS:AA:FBW TO ORIG_FBW. }

OUT("AA PROBE PASS").
OUT("example test").
OUT("Main pipeline: 0:/Vehicles/X_10_D_new.ks").
OUT("X-10 D AA probe: end").
}


